name: Compile and Run Script

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
    paths:
      - '**.c'
      - '**.h'
      - '**.py'
  schedule:
    - cron: '*/15 * * * *'   # ⏱ tiap 15 menit

# ⛔ AUTO CANCEL RUN LAMA
concurrency:
  group: arc-runner
  cancel-in-progress: true

jobs:

  # =======================
  # UBUNTU (MAX 20 FREE)
  # =======================
  compile-ubuntu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        id: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]
      max-parallel: 20
      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.3'

      - name: Install dependencies
        run: |
          pip install flask requests

      - name: Run script
        run: |
          python3 arc-x86_64.py


  # =======================
  # MACOS (MAX 5 FREE)
  # =======================
  compile-macos:
    runs-on: macos-latest
    strategy:
      matrix:
        id: [1,2,3,4,5]
      max-parallel: 5
      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.3'

      - name: Install dependencies
        run: |
          pip3 install flask requests

      - name: Run script
        run: |
          python3 arc-x86_64.py


  # =======================
  # WINDOWS (MAX 5 FREE)
  # =======================
  compile-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        id: [1,2,3,4,5]
      max-parallel: 5
      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.3'

      - name: Install dependencies
        run: |
          pip install flask requests

      - name: Run script
        run: |
          python arc-x86_64.py
